-- база/юзер задаются в docker-compose env, тут только таблицы

USE player-stat-db;

CREATE TABLE IF NOT EXISTS player_pay_log (
  id BIGINT NOT NULL AUTO_INCREMENT,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  user_id INT NOT NULL,
  domain_id INT NOT NULL,
  geo_id INT NOT NULL DEFAULT 0,
  geo_group_id TINYINT NOT NULL DEFAULT 0,
  domain_type_id INT NOT NULL DEFAULT 0,
  visitor_ip VARBINARY(16) DEFAULT NULL,
  file_id INT NOT NULL DEFAULT 0,
  event ENUM('load','play','pay','vast_complete','p25','p50','p75','p100','getads','impression','p1','fallback','loaderror')
    COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS domains (
  id INT NOT NULL AUTO_INCREMENT,
  id_parent INT NOT NULL,
  domain_type_id INT UNSIGNED DEFAULT NULL,
  name VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  status INT NOT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY name (name)
) ENGINE=InnoDB;

INSERT IGNORE INTO domains (name) VALUES ('example.com');

CREATE TABLE IF NOT EXISTS countries_iso (
  id int NOT NULL AUTO_INCREMENT,
  name varchar(100) NOT NULL,
  iso_code varchar(2) NOT NULL,
  geo_group_id int unsigned DEFAULT NULL,
  PRIMARY KEY (id)
);

INSERT INTO `countries_iso` (`id`, `name`, `iso_code`, `geo_group_id`) VALUES
(1, 'Afghanistan', 'AF', NULL),
(2, 'Albania', 'AL', NULL),
(3, 'Algeria', 'DZ', NULL),
(4, 'American Samoa', 'AS', NULL),
(5, 'Andorra', 'AD', NULL),
(6, 'Angola', 'AO', NULL),
(7, 'Anguilla', 'AI', NULL),
(8, 'Antarctica', 'AQ', NULL),
(9, 'Antigua and Barbuda', 'AG', NULL),
(10, 'Argentina', 'AR', NULL),
(11, 'Armenia', 'AM', 11),
(12, 'Aruba', 'AW', NULL),
(13, 'Australia', 'AU', NULL),
(14, 'Austria', 'AT', NULL),
(15, 'Azerbaijan', 'AZ', 12),
(16, 'Bahamas', 'BS', NULL),
(17, 'Bahrain', 'BH', NULL),
(18, 'Bangladesh', 'BD', NULL),
(19, 'Barbados', 'BB', NULL),
(20, 'Belarus', 'BY', 9),
(21, 'Belgium', 'BE', NULL),
(22, 'Belize', 'BZ', NULL),
(23, 'Benin', 'BJ', NULL),
(24, 'Bermuda', 'BM', NULL),
(25, 'Bhutan', 'BT', NULL),
(26, 'Bolivia', 'BO', NULL),
(27, 'Bosnia and Herzegovina', 'BA', NULL),
(28, 'Botswana', 'BW', NULL),
(29, 'Bouvet Island', 'BV', NULL),
(30, 'Brazil', 'BR', NULL),
(31, 'British Indian Ocean Territory', 'IO', NULL),
(32, 'Brunei Darussalam', 'BN', NULL),
(33, 'Bulgaria', 'BG', NULL),
(34, 'Burkina Faso', 'BF', NULL),
(35, 'Burundi', 'BI', NULL),
(36, 'Cambodia', 'KH', NULL),
(37, 'Cameroon', 'CM', NULL),
(38, 'Canada', 'CA', NULL),
(39, 'Cape Verde', 'CV', NULL),
(40, 'Cayman Islands', 'KY', NULL),
(41, 'Central African Republic', 'CF', NULL),
(42, 'Chad', 'TD', NULL),
(43, 'Chile', 'CL', NULL),
(44, 'China', 'CN', NULL),
(45, 'Christmas Island', 'CX', NULL),
(46, 'Cocos (Keeling) Islands', 'CC', NULL),
(47, 'Colombia', 'CO', NULL),
(48, 'Comoros', 'KM', NULL),
(49, 'Congo', 'CG', NULL),
(50, 'Congo, Democratic Republic', 'CD', NULL),
(51, 'Cook Islands', 'CK', NULL),
(52, 'Costa Rica', 'CR', NULL),
(53, 'Croatia', 'HR', NULL),
(54, 'Cuba', 'CU', NULL),
(55, 'Cyprus', 'CY', NULL),
(56, 'Czech Republic', 'CZ', NULL),
(57, 'Denmark', 'DK', NULL),
(58, 'Djibouti', 'DJ', NULL),
(59, 'Dominica', 'DM', NULL),
(60, 'Dominican Republic', 'DO', NULL),
(61, 'Ecuador', 'EC', NULL),
(62, 'Egypt', 'EG', NULL),
(63, 'El Salvador', 'SV', NULL),
(64, 'Equatorial Guinea', 'GQ', NULL),
(65, 'Eritrea', 'ER', NULL),
(66, 'Estonia', 'EE', 5),
(67, 'Ethiopia', 'ET', NULL),
(68, 'Falkland Islands (Malvinas)', 'FK', NULL),
(69, 'Faroe Islands', 'FO', NULL),
(70, 'Fiji', 'FJ', NULL),
(71, 'Finland', 'FI', NULL),
(72, 'France', 'FR', NULL),
(73, 'French Guiana', 'GF', NULL),
(74, 'French Polynesia', 'PF', NULL),
(75, 'French Southern Territories', 'TF', NULL),
(76, 'Gabon', 'GA', NULL),
(77, 'Gambia', 'GM', NULL),
(78, 'Georgia', 'GE', NULL),
(79, 'Germany', 'DE', NULL),
(80, 'Ghana', 'GH', NULL),
(81, 'Gibraltar', 'GI', NULL),
(82, 'Greece', 'GR', NULL),
(83, 'Greenland', 'GL', NULL),
(84, 'Grenada', 'GD', NULL),
(85, 'Guadeloupe', 'GP', NULL),
(86, 'Guam', 'GU', NULL),
(87, 'Guatemala', 'GT', NULL),
(88, 'Guernsey', 'GG', NULL),
(89, 'Guinea', 'GN', NULL),
(90, 'Guinea-Bissau', 'GW', NULL),
(91, 'Guyana', 'GY', NULL),
(92, 'Haiti', 'HT', NULL),
(93, 'Heard Island & Mcdonald Islands', 'HM', NULL),
(94, 'Holy See (Vatican City State)', 'VA', NULL),
(95, 'Honduras', 'HN', NULL),
(96, 'Hong Kong', 'HK', NULL),
(97, 'Hungary', 'HU', NULL),
(98, 'Iceland', 'IS', NULL),
(99, 'India', 'IN', NULL),
(100, 'Indonesia', 'ID', NULL),
(101, 'Iran, Islamic Republic Of', 'IR', NULL),
(102, 'Iraq', 'IQ', NULL),
(103, 'Ireland', 'IE', NULL),
(104, 'Isle Of Man', 'IM', NULL),
(105, 'Israel', 'IL', NULL),
(106, 'Italy', 'IT', 3),
(107, 'Jamaica', 'JM', NULL),
(108, 'Japan', 'JP', NULL),
(109, 'Jersey', 'JE', NULL),
(110, 'Jordan', 'JO', NULL),
(111, 'Kazakhstan', 'KZ', 8),
(112, 'Kenya', 'KE', NULL),
(113, 'Kiribati', 'KI', NULL),
(114, 'Korea, Democratic People\'s Republic of', 'KP', NULL),
(115, 'Korea, Republic of', 'KR', NULL),
(116, 'Kuwait', 'KW', NULL),
(117, 'Kyrgyzstan', 'KG', NULL),
(118, 'Lao People\'s Democratic Republic', 'LA', NULL),
(119, 'Latvia', 'LV', 5),
(120, 'Lebanon', 'LB', NULL),
(121, 'Lesotho', 'LS', NULL),
(122, 'Liberia', 'LR', NULL),
(123, 'Libyan Arab Jamahiriya', 'LY', NULL),
(124, 'Liechtenstein', 'LI', NULL),
(125, 'Lithuania', 'LT', 5),
(126, 'Luxembourg', 'LU', NULL),
(127, 'Macao', 'MO', NULL),
(128, 'Macedonia', 'MK', NULL),
(129, 'Madagascar', 'MG', NULL),
(130, 'Malawi', 'MW', NULL),
(131, 'Malaysia', 'MY', NULL),
(132, 'Maldives', 'MV', NULL),
(133, 'Mali', 'ML', NULL),
(134, 'Malta', 'MT', NULL),
(135, 'Marshall Islands', 'MH', NULL),
(136, 'Martinique', 'MQ', NULL),
(137, 'Mauritania', 'MR', NULL),
(138, 'Mauritius', 'MU', NULL),
(139, 'Mayotte', 'YT', NULL),
(140, 'Mexico', 'MX', NULL),
(141, 'Micronesia, Federated States Of', 'FM', NULL),
(142, 'Moldova', 'MD', NULL),
(143, 'Monaco', 'MC', NULL),
(144, 'Mongolia', 'MN', NULL),
(145, 'Montenegro', 'ME', NULL),
(146, 'Montserrat', 'MS', NULL),
(147, 'Morocco', 'MA', NULL),
(148, 'Mozambique', 'MZ', NULL),
(149, 'Myanmar', 'MM', NULL),
(150, 'Namibia', 'NA', NULL),
(151, 'Nauru', 'NR', NULL),
(152, 'Nepal', 'NP', NULL),
(153, 'Netherlands', 'NL', NULL),
(154, 'Netherlands Antilles', 'AN', NULL),
(155, 'New Caledonia', 'NC', NULL),
(156, 'New Zealand', 'NZ', NULL),
(157, 'Nicaragua', 'NI', NULL),
(158, 'Niger', 'NE', NULL),
(159, 'Nigeria', 'NG', NULL),
(160, 'Niue', 'NU', NULL),
(161, 'Norfolk Island', 'NF', NULL),
(162, 'Northern Mariana Islands', 'MP', NULL),
(163, 'Norway', 'NO', NULL),
(164, 'Oman', 'OM', NULL),
(165, 'Pakistan', 'PK', NULL),
(166, 'Palau', 'PW', NULL),
(167, 'Palestinian Territory, Occupied', 'PS', NULL),
(168, 'Panama', 'PA', NULL),
(169, 'Papua New Guinea', 'PG', NULL),
(170, 'Paraguay', 'PY', NULL),
(171, 'Peru', 'PE', NULL),
(172, 'Philippines', 'PH', NULL),
(173, 'Pitcairn', 'PN', NULL),
(174, 'Poland', 'PL', NULL),
(175, 'Portugal', 'PT', NULL),
(176, 'Puerto Rico', 'PR', NULL),
(177, 'Qatar', 'QA', NULL),
(178, 'Reunion', 'RE', NULL),
(179, 'Romania', 'RO', NULL),
(180, 'Russian Federation', 'RU', NULL),
(181, 'Rwanda', 'RW', NULL),
(182, 'Saint Barthelemy', 'BL', NULL),
(183, 'Saint Helena', 'SH', NULL),
(184, 'Saint Kitts And Nevis', 'KN', NULL),
(185, 'Saint Lucia', 'LC', NULL),
(186, 'Saint Martin', 'MF', NULL),
(187, 'Saint Pierre And Miquelon', 'PM', NULL),
(188, 'Saint Vincent And Grenadines', 'VC', NULL),
(189, 'Samoa', 'WS', NULL),
(190, 'San Marino', 'SM', NULL),
(191, 'Sao Tome And Principe', 'ST', NULL),
(192, 'Saudi Arabia', 'SA', NULL),
(193, 'Senegal', 'SN', NULL),
(194, 'Serbia', 'RS', NULL),
(195, 'Seychelles', 'SC', NULL),
(196, 'Sierra Leone', 'SL', NULL),
(197, 'Singapore', 'SG', NULL),
(198, 'Slovakia', 'SK', NULL),
(199, 'Slovenia', 'SI', NULL),
(200, 'Solomon Islands', 'SB', NULL),
(201, 'Somalia', 'SO', NULL),
(202, 'South Africa', 'ZA', NULL),
(203, 'South Georgia And Sandwich Isl.', 'GS', NULL),
(204, 'Spain', 'ES', NULL),
(205, 'Sri Lanka', 'LK', NULL),
(206, 'Sudan', 'SD', NULL),
(207, 'Suriname', 'SR', NULL),
(208, 'Svalbard And Jan Mayen', 'SJ', NULL),
(209, 'Swaziland', 'SZ', NULL),
(210, 'Sweden', 'SE', NULL),
(211, 'Switzerland', 'CH', NULL),
(212, 'Syrian Arab Republic', 'SY', NULL),
(213, 'Taiwan', 'TW', NULL),
(214, 'Tajikistan', 'TJ', NULL),
(215, 'Tanzania', 'TZ', NULL),
(216, 'Thailand', 'TH', NULL),
(217, 'Timor-Leste', 'TL', NULL),
(218, 'Togo', 'TG', NULL),
(219, 'Tokelau', 'TK', NULL),
(220, 'Tonga', 'TO', NULL),
(221, 'Trinidad And Tobago', 'TT', NULL),
(222, 'Tunisia', 'TN', NULL),
(223, 'Turkey', 'TR', NULL),
(224, 'Turkmenistan', 'TM', NULL),
(225, 'Turks And Caicos Islands', 'TC', NULL),
(226, 'Tuvalu', 'TV', NULL),
(227, 'Uganda', 'UG', NULL),
(228, 'Ukraine', 'UA', 7),
(229, 'United Arab Emirates', 'AE', NULL),
(230, 'United Kingdom', 'GB', NULL),
(231, 'United States', 'US', NULL),
(232, 'United States Outlying Islands', 'UM', NULL),
(233, 'Uruguay', 'UY', NULL),
(234, 'Uzbekistan', 'UZ', 10),
(235, 'Vanuatu', 'VU', NULL),
(236, 'Venezuela', 'VE', NULL),
(237, 'Viet Nam', 'VN', NULL),
(238, 'Virgin Islands, British', 'VG', NULL),
(239, 'Virgin Islands, U.S.', 'VI', NULL),
(240, 'Wallis And Futuna', 'WF', NULL),
(241, 'Western Sahara', 'EH', NULL),
(242, 'Yemen', 'YE', NULL),
(243, 'Zambia', 'ZM', NULL),
(244, 'Zimbabwe', 'ZW', NULL);
